Add m (math) library to libs.private (pkg-config) if it is used
This should get rid of "undefined reference to `log2'" errors when
using pkg-config and using the static library.